### ISSUE TITLE
sound not playing on safari iOS

### ISSUE THREAD

**Issue by lmssiehdev** [lmssiehdev/calmwhisper#1]
some users reported that the sound isn't playing on safari. sadly, I don't have access to an iOS device so I am unable to test it myself.

if anyone is interested in fixing this or helping me troubleshoot it please let me know.

**Comment by s-hens** [comment]
I believe the sound is not playing on Safari/iOS because Safari/iOS does not support the .ogg file type.

StackOverflow threads that might help:
[How to play/decode Ogg Opus Audio in Safari?](https://stackoverflow.com/questions/62216863/how-to-play-decode-ogg-opus-audio-in-safari)
[safari doesn't play .ogg files, so how does it work on wiktionary.org?](https://stackoverflow.com/questions/38581887/safari-doesnt-play-ogg-files-so-how-does-it-work-on-wiktionary-org)

I hope this helps to point you in the right direction. Unfortunately, I am also unable to do full testing on iOS devices myself. I'm not sure what the best workaround would be, other than using a different audio file type.

I'm trying to begin a community-maintained [repository of iOS web dev issues](https://github.com/s-hens/ios-friendly-web-dev) like this one, so please let me know if you find a solution.

**Comment by lmssiehdev** [comment]
yep, that's most likely the issue, I have changed the file format from .ogg to .mp3, can you confirm that the issue has been solved https://yume-6m7qcm76d-lmssiehdev.vercel.app/

**Comment by s-hens** [comment]
I am not able to do full-fledged testing/debugging for iOS/Safari, best I can do is open the link on my iPhone 6S. Unfortunately, the issue is not fixed -- still no sound.

**Comment by anon4747** [comment]
> yep, that's most likely the issue, I have changed the file format from .ogg to .mp3, can you confirm that the issue has been solved https://yume-6m7qcm76d-lmssiehdev.vercel.app/

Hey, I have an iOS device. The buttons are not working, so I can't select a sound on my iPhone.

**Comment by lmssiehdev** [comment]
I already figured out what's causing the issue, I'll be fixing it shortly.

**Comment by lmssiehdev** [comment]
I initially only changed the file extension from ".ogg" to ".mp3" without converting the format 😅, but I have fixed it now.

Let me know if any further issues arise.

**Comment by anon4747** [comment]
Well, you "converted" it manually 😜
I tested it, but it's not background playing and I also have to use the ringer to hear sound.
Could you find a way for that please?

**Comment by lmssiehdev** [comment]
I don't have access to any iOS device, so it will be really hard for me to investigate and fix these issues.
